### ISSUE TITLE
Add a document to an envelope using a Stream

### ISSUE THREAD

**Issue by jessebarocio** [docusign/DocuSign-.NET-Client#10]
Right now `Envelope.Create()` has overloads that take a path or a byte array. There should be an overload that takes a `Stream`. 

If I have a Stream I don't want to have to write the file to disk just so I can get a path and I may not want to load the whole thing into memory to get a byte array either.

**Comment by InbarGazit** [comment]
@jessebarocio this is a really good suggestion. We would love to implement it. If you already wrote this overload - feel free to submit your code and we might take your contribution.
Thanks for your feedback!

**Comment by InbarGazit** [comment]
@jessebarocio , I have pushed an update with the new overload you asked for. Let me know if this is what you had in mind. We'll update the nuget package later.
