### ISSUE TITLE
Missing functionality

### ISSUE THREAD

**Issue by markjritchie** [docusign/DocuSign-.NET-Client#14]
I've recently joined a team that was starting to interface with DocuSign, they had not discovered the .NET client and had been hand rolling their own Rest requests. I'm in the process of migrating what they have done to use the client but cannot find some features that they have been using and are not present:

* SmsAuthentication
* EmailNotification

Are they implemented and just not obvious or are they scheduled to be implemented?

**Comment by InbarGazit** [comment]
Mark, thanks for your feedback. At present time we don't have these in the library. We would love to add them. One of the reasons we have both a nuget package and the open source on git is that anyone can contribute. If you feel you can add these yourself - that would be great. Not sure when we can get to it on our end, this is the first time these have been requested, but I agree these are important.

**Comment by markjritchie** [comment]
I guess I'll have a go at adding the features we need, I'll have to speak to the people here to see if its acceptable to push the changes I have to make to get things working.

**Comment by InbarGazit** [comment]
@markjritchie we have just released version 1.4 with additional features including SMS notification support. You can see the new code here. thanks

**Comment by InbarGazit** [comment]
We have added these missing features. closing
