### ISSUE TITLE
URI not properly formatted

### ISSUE THREAD

**Issue by dunsmonj** [docusign/DocuSign-.NET-Client#15]
I am trying to replicate your example and during 	bool result = account.Login(); I am getting a URI format error. Is there a input im missing? is anyone else encountering this issue?

Im doing

Account account = new Account();
account.Email = AccountEmail;
account.Password = AccountPassword;

Iv used prod and sandbox credentials for AccountEmail and AccountPassword to no luck.

I am not sure if this is an issue with the nugget or not thats why I posted here first until I go over to stacks. Which it might be because I get 

An exception of type 'System.UriFormatException' occurred in DocuSign.Integration.Client.dll but was not handled in user code

Additional information: Invalid URI: The format of the URI could not be determined.
Any suggestions?

**Comment by InbarGazit** [comment]
@dunsmonj , you might be forgetting to instantiate some of the RestSettings before you start doing any sort of API requests. Can you post your full code? look mostly at the DocuSign.Integrations.Client.RestSettings.Instance.WebServiceUrl and make sure it's set properly.

**Comment by dunsmonj** [comment]
Sure, it fails at account.login()



using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DocuSign.Integrations.Client;
using System.Threading.Tasks;
using System.IO;
using System.Diagnostics;
using System.Text;

namespace DocuSignz.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}

		public ActionResult NewHire()
		{
			string AccountEmail = "test@gmail.com";
			string AccountPassword = "1234";
			string RecipientEmail = "test2@gmail.com";
			string RecipientName = "dunsmonj";
			string TemplateId = "44F554FC-C88D-440C-A9BE-DF854058ABCB";
			string TemplateRoleName = "test";

			// user credentials 
			Account account = new Account();
			account.Email = AccountEmail;
			account.Password = AccountPassword;

			// make the login call (retrieves your baseUrl and accountId)
			bool result = account.Login();
			if (!result)
			{
				Console.WriteLine("Login API call failed for user {0}.\nError Code:  {1}\nMessage:  {2}", account.Email, account.RestError.errorCode, account.RestError.message);
			}
			// create envelope object and assign login info
			Envelope envelope = new Envelope();
			envelope.Login = account;

			// use an existing server template
			envelope.TemplateId = TemplateId;

			// add one signer to a template role identified by roleName
			envelope.TemplateRoles = new TemplateRole[]
            {
                new TemplateRole()
                {
                    email = RecipientEmail,
                    name = RecipientName,
                    roleName = TemplateRoleName
						  // Put in for loop routingOrder
                }
            };

			// Email subject is a required parameter when requesting signatures
			envelope.EmailSubject = "DocuSign .NET Client - Signature Request from Template";

			// "sent" to send immediately, "created" to save envelope as draft
			envelope.Status = "sent";

			// create and send the envelope (since status is set to "sent")
			result = envelope.Create();

			if (!result)
			{
				if (envelope.RestError != null)
				{
					Console.WriteLine("Error code:  {0}\nMessage:  {1}", envelope.RestError.errorCode, envelope.RestError.message);
				}
				else
				{
					Console.WriteLine("Error encountered while requesting signature from template, please review your envelope and recipient data.");

				}
			}


			return View();
		}
	}
}

**Comment by dunsmonj** [comment]
I think you were correct about WebServiceUrl, I am testing

**Comment by InbarGazit** [comment]
You are also missing the integrator key... do you have one you can use?

**Comment by dunsmonj** [comment]
Awesome! It was a foolish mistake on my part. Thank you. Below is my MVC action. Thank you

	public ActionResult NewHire()
		{
			const string IntegratorKey = "***";
			const string Environment = "http://demo.docusign.net";
			RestSettings.Instance.IntegratorKey = IntegratorKey;
			RestSettings.Instance.DocuSignAddress = Environment;
			RestSettings.Instance.WebServiceUrl = Environment + "/restapi/v2";


			string AccountEmail = "***";
			string AccountPassword = "***";
			string RecipientEmail = "****";
			string RecipientName = "***";
			string TemplateId = "44F554FC-C88D-440C-A9BE-DF854058ABCB";
			string TemplateRoleName = "test";

			// user credentials 
			Account account = new Account();
			account.Email = AccountEmail;
			account.Password = AccountPassword;

			// make the login call (retrieves your baseUrl and accountId)
			bool result = account.Login();
			if (!result)
			{
				Console.WriteLine("Login API call failed for user {0}.\nError Code:  {1}\nMessage:  {2}", account.Email, account.RestError.errorCode, account.RestError.message);
			}
			// create envelope object and assign login info
			Envelope envelope = new Envelope();
			envelope.Login = account;

			// use an existing server template
			envelope.TemplateId = TemplateId;

			// add one signer to a template role identified by roleName
			envelope.TemplateRoles = new TemplateRole[]
            {
                new TemplateRole()
                {
                    email = RecipientEmail,
                    name = RecipientName,
                    roleName = TemplateRoleName
						  // Put in for loop routingOrder
                }
            };

			// Email subject is a required parameter when requesting signatures
			envelope.EmailSubject = "DocuSign .NET Client - Signature Request from Template";

			// "sent" to send immediately, "created" to save envelope as draft
			envelope.Status = "sent";

			// create and send the envelope (since status is set to "sent")
			result = envelope.Create();

			if (!result)
			{
				if (envelope.RestError != null)
				{
					Console.WriteLine("Error code:  {0}\nMessage:  {1}", envelope.RestError.errorCode, envelope.RestError.message);
				}
				else
				{
					Console.WriteLine("Error encountered while requesting signature from template, please review your envelope and recipient data.");

				}
			}


			return View();
		}

**Comment by InbarGazit** [comment]
no worries, we all learn from mistakes and I'm glad to help. Don't hesitate to ask here if you run into any more issues.
