### ISSUE TITLE
Envelope.GetRecipientView method always return UNKNOWN_ENVELOPE_RECIPIENT

### ISSUE THREAD

**Issue by Grievoushead** [docusign/DocuSign-.NET-Client#2]
```
requestInfo.RequestBody = new List<RequestBody>()
        {
          new RequestBody()
          {
            Text = new RecipientView()
            {
              returnUrl = returnUrl,
              email = this.Login.Email,
              userName = this.Login.AccountName,
              authenticationMethod = "email"
            }.Serialize()
          }
        }.ToArray();
```
 i think it's b/c in GetRecipientView method in req body email is account email but it should be recipient email.

**Comment by InbarGazit** [comment]
to use this method you need to specify the envelopeId for the Envelope and you need to specify the Login element as a valid Account object. Did you have both of them when you tried this?

**Comment by Grievoushead** [comment]
@InbarGazit yes, but I need to have different user as recipient then in the Login, but here the username is taken from the Login

**Comment by sergproua** [comment]
It's not working for me either, clientUserId property is not defined in TemplateRole class which is required to Launch the Embedded Signing view (aka recipient view).

from https://www.docusign.com/developer-center/explore/features/embedding-docusign
```
On a given envelope if a recipient does not have the clientUserId element defined then the recipient is a remote recipient, and requests to them will be initiated through email notifications. On the other hand, if the clientUserId is present and it's value is not null then the recipient is an embedded recipient, and they can access the envelope through a URL token instead of a hyperlink in an email.
```

**Comment by InbarGazit** [comment]
@sergproua , we'll be adding support for embedded signing (adding clientUserId) in a version we plan to have out very soon. In the meantime you can use regular signing or you can add it yourself.

**Comment by InbarGazit** [comment]
@Grievoushead the GetRecipientView method is for a self-signed envelope where only the person sending it is the only signer and that's how you sign it. Like I told @sergproua , we'll be adding support for embedded signing very soon.

**Comment by InbarGazit** [comment]
@sergproua  , wanted to also personally invite you to our very first developer conference to be held this coming March in San Francisco. this is exactly the opportunity to meet me and other developers in DocuSign and talk shop. And the cost is very low. See all the information here http://momentum.docusign.com/san-francisco/dev-con/?mc=devcon-github

**Comment by InbarGazit** [comment]
@Grievoushead  , wanted to also personally invite you to our very first developer conference to be held this coming March in San Francisco. this is exactly the opportunity to meet me and other developers in DocuSign and talk shop. And the cost is very low. See all the information here http://momentum.docusign.com/san-francisco/dev-con/?mc=devcon-github

**Comment by Grievoushead** [comment]
@InbarGazit thanks, I would really like to visit conf :) will wait for new version of client :+1:

**Comment by InbarGazit** [comment]
@Grievoushead , new version is here. We added clientUserId and a new method to get embedded signing URL. the new nuget is version 1.2.0 and the code is already pushed. Let me know if you have any questions.

**Comment by Grievoushead** [comment]
@InbarGazit Great! Thanks!

**Comment by sergproua** [comment]
@InbarGazit - Thanks for the invite, I would like to join however cannot make it to SF until later this year. If you planning another gig on the East cost, I'm game!

RecepientRole class needs clientUserId as well when creating an envelope with a template.

**Comment by InbarGazit** [comment]
thanks @sergproua , we'll get it in a future release. Hoping to keep updating the code and the library on a regular basis,

**Comment by InbarGazit** [comment]
@sergproua , just clarifying you mean the TemplateRole class, correct?

**Comment by InbarGazit** [comment]
this was added in version 1.2.1. I'm closing this issue as resolved, please let me know if you still need assistance.

**Comment by InbarGazit** [comment]
@sergproua  and @Grievoushead we're looking for a developer who is using the library to share their experience in the coming conference (I know it's a short notice, it's 2 weeks from now). We can compensate you for your ticket if you can present. Is that something you might be interested in?
