### ISSUE TITLE
1.4 is not Strongly Named

### ISSUE THREAD

**Issue by aw232** [docusign/DocuSign-.NET-Client#21]
In order to support a com interop project I needed to add the dll to a GAC.  the assembly needs to be strongly named to do this.  For my own project I simply pulled down the latest, added the necessary options, and it worked just fine.  I just thought I'd bring it up so others don't have to go through that.  Thanks.

**Comment by InbarGazit** [comment]
Latest version (1.5) of the nuget package (https://www.nuget.org/packages/DocuSign.Integration.Client.dll/) is now strong name signed. Let me know if this doesn't resolve your issue.
