### ISSUE TITLE
Again Missing features

### ISSUE THREAD

**Issue by MattyBoy4444** [docusign/DocuSign-.NET-Client#25]
This client is mostly useless, I think??  There is NO support for adding signature tabs or any other tab except text tabs.  Am I missing something?

**Comment by InbarGazit** [comment]
Matt, there is support for adding many different type of tabs. The full list includes:

            tabs.checkboxTabs = null;
            tabs.companyTabs = null;
            tabs.dateSignedTabs = null;
            tabs.emailTabs = null;
            tabs.fullNameTabs = null;
            tabs.initialHereTabs = null;
            tabs.signerAttachmentTabs = null;
            tabs.signHereTabs = null;
            tabs.textTabs = null;
            tabs.titleTabs = null;

(this is a code snippet that I just copy/pasted, but you get the idea)

**Comment by MattyBoy4444** [comment]
Ya but there is no way with the c# API to add the tabs.  AddTabs only adds textTabs.

**Comment by InbarGazit** [comment]
TabCollection tabs = new TabCollection();

            List<Tab> signHereTabs = new List<Tab>();

            var tab = new Tab();

            tab.xPosition = int.Parse(textBox7.Text);
            tab.yPosition = int.Parse(textBox8.Text);
            tab.tabLabel = textBox9.Text;
            tab.pageNumber = 1;
            tab.documentId = 1;
            tab.tabId = "1";
            tab.recipientId = "1";
            signHereTabs.Add(tab);

            tabs.signHereTabs = signHereTabs;
            
            if (myEnvelope.AddTabs(tabs))

**Comment by InbarGazit** [comment]
this example is part of a winform demo code and it adds a signature tab. Similarly you can add all other tab types

**Comment by MattyBoy4444** [comment]
Again, look at AddTabs code.  It only enumerates the textTabs List

**Comment by InbarGazit** [comment]
it works, I can assure you. What you are seeing is that we only add tabLabel for textTabs list which are the only onnes that need it but we serialize the entire Tabs object and all tab types are added. I have working demo here on my box.

**Comment by MattyBoy4444** [comment]
K.  just looked weird when I looked at it quick.  My bad!

**Comment by InbarGazit** [comment]
ok, please do let me know if something doesn't work right (and it's ok if it's looking weird, I agree looks are important too). I'm closing this for now. thanks!
