### ISSUE TITLE
Getting key file import failure upon forking

### ISSUE THREAD

**Issue by alexed1** [docusign/DocuSign-.NET-Client#29]
We cloned this library a few days ago and were able to successfully build it, although we did have to manually copy "nuget.exe" into the .nuget folder.

We then tried, today, to fork the repo. We forked and cloned. When we tried to build from the new clone, we again got the nuget.exe error and again fixed it. Then, however, we got this error: 

__"Cannot import the following key file: DocuSignClient.pfx. The key file may be password protected. To correct this, try to import the certificate again or manually install the certificate to the Strong Name CSP with the following key container name: VS_KEY_6CA6AFBE065420C2  "__

Based on SO, we used the sn command, but it wants a password:

__c:\code\DocuSign-.NET-Client\DocuSign.Integrations.Client>sn -i DocuSignClient.p
fx VS_KEY_6CA6AFBE065420C2__

__Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.
Enter the password for the PKCS#12 key file:
Failed to parse the PKCS#12 blob in DocuSignClient.pfx -- The specified network
password is not correct.__

These might be very stupid questions, but:
1) Is this a new problem that we've stumbled on?
2) Do we need to request a password from Docusign before we fork the repo? Or is forking not allowed at all?
3) Are we just doing something dumb here? 

cheers

**Comment by InbarGazit** [comment]
Sorry @alexed1 my bad. I just pushed an update to change from .pfx to .snk which should resolve your issue.
this was done so you can strong-name-sign your assembly and this way you can GAC it

Let me know if you still have an issue once you pull latest.

**Comment by InbarGazit** [comment]
didn't hear anything new, so I Assume this is good now, closing....
