### ISSUE TITLE
Exceptions for UpdateStatus and SendReminder

### ISSUE THREAD

**Issue by dman7529** [docusign/DocuSign-.NET-Client#30]
I am getting the following error code when I call the UpdateStatus and SendReminder methods from Envelope.
Error code: INVALID_REQUEST_PARAMETER Message: The request contained at least one invalid parameter. Query parameter 'from_date' must be set to a valid DateTime, or 'envelope_ids' or 'transaction_ids' must be specified.
I have a valid envelope, and can use the GetStatus  method to return the proper creation time, but the above methods are throwing the exception.

**Comment by InbarGazit** [comment]
@dman7529, can you share the code (or snippet) that you're running?

**Comment by dman7529** [comment]
I'm using the Examples code to test other aspects of the API, so the below code is setup in that fashion.

Envelope envelope = new Envelope();
envelope.Login = account;

DateTime sentTime = envelope.GetStatus(EnvelopeId);

envelope.SendReminder();

**Comment by dman7529** [comment]
I was able to fix the SendReminder issue by setting the envelopes ID, which I thought I had tried before.  I still have an issue with UpdateStatus.  I changed its code so that like SendReminder, the envelopes ID is being set, and no longer get the INVALID REQUEST PARAMETER error.  However, whether a void reason is given or not, UpdateStatus, does not update the status of the envelope.

Envelope envelope = new Envelope();
envelope.Login = account;
envelope.EnvelopeId = envelopeID;

if (string.IsNullOrEmpty(voidReason))
{
      envelope.UpdateStatus(); 
}
else
{
     envelope.UpdateStatus(voidReason);
}
            
            if (envelope.RestError != null)
            {
                throw new Exception(string.Format("Error code:  {0}\nMessage:  {1}", envelope.RestError.errorCode, envelope.RestError.message));
            }

**Comment by InbarGazit** [comment]
I don't see you setting the status itself? where do you do that?

**Comment by InbarGazit** [comment]
envelope.Status = "sent" // for example
just before you call UpdateStatus()

**Comment by dman7529** [comment]
Well I had that in a previous attempt, but it gives this exception:
The request contained at least one invalid parameter. Value for 'voidedReason' must be specified when voiding an envelope.
![void envelope](https://cloud.githubusercontent.com/assets/13382913/8907630/dda4409a-343c-11e5-91b8-148a0a351916.png)

**Comment by InbarGazit** [comment]
can you use fiddler to see the actual JSON request being sent? it appears to me like you're still missing the voidedReason which is required in this case but what's weird is we do check for this in the code:

                if (this.Status == "voided") {

                    if (String.IsNullOrEmpty(voidedReason))
                        throw new ArgumentException("The voided reason is required to change status to voided.");

                    sb.AppendFormat(", \"voidedReason\":\"{0}\"", voidedReason);
                }

so, if it was empty - you should have gotten an ArgumentException. Are you running against latest version? I think this was added a few versions ago...

**Comment by dman7529** [comment]
After seeing your response, I realized the problem was that like in other places in the Docusign api, if you don't have some cased correctly, it will throw an exception.  

envelope.Status = "voided";
envelope.UpdateStatus(voidReason);

works.

**Comment by InbarGazit** [comment]
good catch.closing
