### ISSUE TITLE
Document prefill 

### ISSUE THREAD

**Issue by karpenberg** [docusign/DocuSign-.NET-Client#38]
Hello!
I use the latest 1.6 version of library.
I create envelope by template and define TemplateRole for each recipient.  My question: Is there any way to set in code some of tab values for recipient?

**Comment by InbarGazit** [comment]
@karpenberg I think I didn't get this question before. Usually, when using templates the tabs are already defined by the template. I guess you want to add/change tabs using the API after the fact, right?
I'll need to play with it and see, I don't know off hand. Logically this should be supported unless the template restricts it. Did you try it and get some error? I can look into it later in the day and get back to you.

**Comment by karpenberg** [comment]
Thank you for feedback!
  "I guess you want to add/change tabs using the API after the fact, right?"
I want to set value for one of tab and this value I get from my system for each recipient (each value for each recipient). As a result this value should be default value for field on document.
  "Did you try it and get some error?"
I was playing with TemplateRole tabs field but there was no any effect.

**Comment by karpenberg** [comment]
I figured out what the problem was.
I set value to text tab but this tab is type "Company" in template.
Sorry for inconvenience

**Comment by InbarGazit** [comment]
no trouble at all. I'm glad you got it working and I hope maybe future people reading this would find it useful for them. If you have any other questions - feel free to post here.
