### ISSUE TITLE
Any guidance on adding OAuth Token Support?

### ISSUE THREAD

**Issue by alexed1** [docusign/DocuSign-.NET-Client#42]
We're about to incorporate OAuth tokens into our application. It appears that there's no support yet in this Library. We can think of a couple of approaches for adding it, but before we dig in, I wanted to first check and see if there are any existing discussions, any work in progress, or any preferred DocuSign approach that we should know about. We may be very late to the table on this issue....

We saw a thread about this over on the Node client, but it didn't seem heavily developed.
Alex
Dockyard

**Comment by InbarGazit** [comment]
@alexed1 can you explain what you mean by OAuth token support? where do you get the OAuth token from? is it from DocuSign or from what we used to call "Social" login?
We're going to add support for new OAuth mechanism for login which is being developed here soon, but since it's not out yet - I wasn't sure that's what you meant.

**Comment by alexed1** [comment]
This is the scenario where we offer a service that makes use of DocuSign. Our user (an existing DocuSign account holder) starts on our site, we initiate an OAuth session with DocuSign , they provide login credentials, We pass those to DocuSign and don't save them, and   DocuSign grants us an access token. We then provide that token in the REST header to make calls against their DocuSign account.

We're playing around with ideas like this:
 
1. Modify RequestBuilder.MakeRESTRequest()

Add an optional string parameter called authToken that is set by default to ""
example: Requestbuilder builder = new RequestBuilder(authToken="")
Inside the method, add this:
if authToken != "" then SetAuthorizationHeader(authToken);
 
2. Add the method RequestBuilder.SetAuthorizationHeader(string authToken)
SetAuthorizationHeader should add the appropriate OAuth header value to the request.

3. Each method that wished to support authtokens would need to be revised to take an optional auth parameter:
public JObject GetTemplate(string templateId, string authToken="")

However, if you're about to add it yourselves soon, it might make sense to not bother tinkering with the .NET Library and just make direct RESTful calls until you release official support....

**Comment by InbarGazit** [comment]
so @alexed1  if I understand this right, I believe what you are trying to do is available with the library/nuget as it is now. 
after the initial login, you get back something we call ApiPassword (see it in the code) and while it's not technically OAuth, it works just like what you described above. You can use it to make API calls without having to know the password. You do need an integrator key, which I assume you already have, but simply using this ApiPassword (and email address, you do need to know the email of the user) you can fill the Account object and then use it or the Envelope class directly. let me know if this is not clear or this is not what you're trying to do.

**Comment by alexed1** [comment]
Thanks.  Can you elaborate on "after the initial login you get back the ApiPassword":

I'm assuming you mean that on that particular login, we are submitting the customer's email address and their password, and getting back their ApiPassword. Is that correct? Does that mean that we don't use OAuth at all to access DocuSign programmatically on behalf of other DocuSign users? 

How long is the ApiPassword valid? Is it like an OAuth token in that it's valid until the user revokes it?

Is there a reason you recommend this approach instead of OAuth?

Many thanks
Alex
Dockyard
www.dockyard.company

**Comment by InbarGazit** [comment]
let me answer all your questions in order:

1. Correct. You get it back from the first call where you do provide the user's password.
2. You don't use oauth. As for making calls "on behalf of" we support this as well, but that's a whole different topic. For future API calls you can provide a user that is used on behalf of even if the initial auth is using a different user. This requires some settings to be set on the account, but it works.
3. APIPassword is valid until it is revoked, just like you said
4. Right now we don't have oauth support, so this is the next best thing

Hope this helps

Inbar

**Comment by alexed1** [comment]
Thanks. I think that gives us everything we need to know.
