### ISSUE TITLE
How to set the request timeout

### ISSUE THREAD

**Issue by dugbuzz** [docusign/DocuSign-.NET-Client#43]
I notice that the RequestInfo object has a Timeout property which gets applied to the WebRequest if it is set. However, I don't see a way to set the Timeout on RequestInfo. Am I missing something?

**Comment by InbarGazit** [comment]
@dugbuzz you are absolutely right! there's no way to set it.
I guess there was no demand for this so far so no one noticed this.
I can add it for you, but there are 2 ways to do it:
1. Global RestSettings property
2. Per call parameter

What do you think? I think the former would make more sense. Not sure it makes sense to change the timeout for each call. 
Also, I can add it quickly (i.e. right now, today) to GitHub, but publishing a new nuget might have to wait until next week. Is this ok?

**Comment by dugbuzz** [comment]
Hi Inbar, thanks for the quick response!
I'm not so sure there shouldn't be a way to set it per call. I, for example, would want a different timeout for authenticating vs sending a document. Maybe you could make it an optional parameter so it doesn't need to be set on every call?
Next week should be fine for an update. Thanks again! Doug 


     On Thursday, September 3, 2015 1:05 PM, Inbar Gazit <notifications@github.com> wrote:
   

 @dugbuzz you are absolutely right! there's no way to set it.
I guess there was no demand for this so far so no one noticed this.
I can add it for you, but there are 2 ways to do it:
1. Global RestSettings property
2. Per call parameterWhat do you think? I think the former would make more sense. Not sure it makes sense to change the timeout for each call. 
Also, I can add it quickly (i.e. right now, today) to GitHub, but publishing a new nuget might have to wait until next week. Is this ok?—

**Comment by InbarGazit** [comment]
ok, I hear you. I'm still not sure we want to add a timeout parameter for every call we have.
I think we can still use the RestSettings object. You can change it at any time in between calls. Would that work?

**Comment by dugbuzz** [comment]
I'm only sending one request at a time so it'll work for me. Thanks! 


     On Thursday, September 3, 2015 1:42 PM, Inbar Gazit <notifications@github.com> wrote:
   

 ok, I hear you. I'm still not sure we want to add a timeout parameter for every call we have.
I think we can still use the RestSettings object. You can change it at any time in between calls. Would that work?—

**Comment by InbarGazit** [comment]
@dugbuzz just pushed the changes, please take a look and let me know if you think that's going to be good enough for you. if so - I'll go ahead and close this issue and like I said - new package will come next week.

**Comment by dugbuzz** [comment]
Looks good! Thanks a ton!
Doug 


     On Thursday, September 3, 2015 2:36 PM, Inbar Gazit <notifications@github.com> wrote:
   

 @dugbuzz just pushed the changes, please take a look and let me know if you think that's going to be good enough for you. if so - I'll go ahead and close this issue and like I said - new package will come next week.—

**Comment by InbarGazit** [comment]
we'll release this very soon as nuget 1.6.2. Closing...
