### ISSUE TITLE
GetRecipientView REST Error ACCOUNT_NOT_AUTHORIZED_FOR_ENVELOPE

### ISSUE THREAD

**Issue by robertWeller** [docusign/DocuSign-.NET-Client#44]
I am trying to integrate DocUSign embedded signing for my application, however, every time I try to execute the function GetRecipientView I get the REST error ACCOUNT_NOT_AUTHORIZED_FOR_ENVELOPE.

Everything is returning true for result up to the point where GetRecipientView is called and if I modify the code below to comment out the line where it calls GetRecipientView I get the SenderView just fine but I need a SignerView.

I am trying to work off an existing template that I made in the developer center.

```
// user credentials 
                Account account = new Account();
                account.Email = AccountEmail;
                account.Password = AccountPassword;

                // make the login call (retrieves your baseUrl and accountId)
                bool result = account.Login(); //result returns true
                if (!result)
                {                    
                    return BadRequest("Login API call failed for user" + account.Email + ".\nError Code:  " + account.RestError.errorCode + "\nMessage:  " + account.RestError.message);
                }

                // create envelope object and assign login info
                Envelope envelope = new Envelope();
                envelope.Login = account;
                envelope.Status = "sent";
                // use an existing server template
                envelope.TemplateId = TemplateId;

                // add one signer to a template role identified by roleName
                envelope.TemplateRoles = new TemplateRole[]
                {
                    new TemplateRole()
                    {
                        email = RecipientEmail,
                        name = RecipientName,
                        roleName = TemplateRoleName,
                        clientUserId = "101"
                    }
                };


                // create a new DocuSign envelope (i.e. server side)
                result = envelope.Create(); //result returns true

                // generate the recipient view token                
                result = envelope.GetRecipientView(); //returns false, Rest Error = ACCOUNT_NOT_AUTHORIZED_FOR_ENVELOPE

if (!result)
                {
                    if (envelope.RestError != null)
                    {
                        return BadRequest("Error code:  "+ envelope.RestError.errorCode + "\nMessage:  " + envelope.RestError.message);
                    }
                    else
                    {
                        Console.WriteLine();
                        return BadRequest("Error encountered retrieving signing token, please review your envelope and recipient data.");
                    }
                }
                else
                {
                    // open the recipient view (SenderViewUrl field is re-used for the recipient URL)
                    return Ok(envelope.SenderViewUrl);
                }
```

Is this a known issue or am I missing something?

**Comment by InbarGazit** [comment]
@robertWeller did you figure it out? I believe you need to send the envelope first before you can get a recipientView. I see you closed this so I hope you're all set, if not - feel free to ask more questions.

**Comment by robertWeller** [comment]
@InbarGazit What function would you use to send the envelope to enable the signer to sign?

I'm trying to set up an Iframe on a page that would generate the signer window.

**Comment by InbarGazit** [comment]
well, you can either create the envelope in "Sent" status right away or you can use UpdateStatus() to change it to sent status after you created it. let me know if you want a code snippet for this

**Comment by robertWeller** [comment]
@InbarGazit After I instantiate the envelope object I set the Account and Status.

Using Visual Studio 2015 I can see the Status property is persistent after the Create is executed.

Is it case sensitive as I have it as "sent" and not "Sent"

**Comment by InbarGazit** [comment]
lower case is correct.
do you see the envelope if you go to DocuSign? is it in "Draft" mode?
I suspect because it's a template you may need to do this in 2 phases. Create it first and then send it
You can use UpdateStatus() (make sure the status is still "sent") after it was created.

**Comment by robertWeller** [comment]
I do see the envelope and it is in a "Waiting For Others" mode with the correct recipient information which I typed in off my page.

**Comment by InbarGazit** [comment]
oh, ok, so it is sent, I was wrong. this is a different issue.
OK, so if it's waiting for others, you cannot sign it. Do you want to provide someone else the ability to sign it? for that - you'll need to either have their login information or use embedded signing which require to provide clientUserId for the recipients. 
can you explain a bit more what you're trying to do?

**Comment by robertWeller** [comment]
I'm trying to do embedded signing. 

Under template roles I am assigning a new template role which has a clientUserId of 101.

**Comment by InbarGazit** [comment]
did you try to use the GetEmbeddedSignerView() on the Envelope object?

**Comment by robertWeller** [comment]
That was it, I had to make a Signer object which I cloned the information from Template Role I created.

Thank you for help, very helpful. :triumph:

**Comment by InbarGazit** [comment]
no prob, anytime.
