### ISSUE TITLE
Adding Custom Fields to Documents on an Envelope

### ISSUE THREAD

**Issue by Patman0021** [docusign/DocuSign-.NET-Client#48]
I have been looking through the API trying to find the following call:
[https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#REST%20API%20References/Add Custom Document Fields to an Envelope Document.htm](https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#REST%20API%20References/Add Custom Document Fields to an Envelope Document.htm)

I haven't been able to find it, so I'm assuming that I'm going to have to add it, unless I'm just looking in all the wrong places.

**Comment by InbarGazit** [comment]
@Patman0021 you are correct. I believe this is the first time this has come up. You can add custom envelope fields via the API, but not custom document fields. I guess you can always add a prefix to the field telling you what document it's for and workaround this limitation or you can add this like you suggested. If you do end up adding it and you feel like sharing - this might benefit the rest of the community. let us know!

**Comment by InbarGazit** [comment]
this was added and is in version 1.6.3
