### ISSUE TITLE
Send Request from Template and add extra Document?

### ISSUE THREAD

**Issue by purj0001** [docusign/DocuSign-.NET-Client#53]
I need to send a signature request from a Template (easy enough by adding a TemplateId and TemplateRoles)…but also add a document into the envelope. Basically standard template housed in DocuSign for signing, but need to be able to also add a document just for supporting documentation into the envelope (no signing needed on this..just appended to the end)….is this possible?

Thanks!

**Comment by InbarGazit** [comment]
@purj0001 have you tried to create the envelope from template and then call the AddDocment() method? 
as long as the envelope is in "draft" state (not sent yet) you should be able to add/remove documents (even if it's created from template).
The new document would not have any tags unless you add them from API though...

**Comment by purj0001** [comment]
Thanks for the quick response!
That was it - I had it in the wrong order...i was trying to AddDocument() before calling Create. 

Now its sitting in Draft state, how can I then send it on for signature? I tried immediately following the AddDocument() call to set the Status to "sent" and then use UpdateStatus() but that didn't seem to work. Do i need to call something else after the UpdateStatus()?

Thanks!

**Comment by InbarGazit** [comment]
well, I suspect something is not right and you might be able to find more information in the RestError object of the Envelope class you're using. there may be a problem with the recipients maybe?

**Comment by purj0001** [comment]
Yep, that's exactly what it was. I just needed to reset the Recipients and call UpdateRecipients before the UpdateStatus call.

Thanks so much for your help! I've completed what I was trying to do so i'll close this ticket.

Thanks again!

**Comment by kslemmer** [comment]
Hey, this is the exact functionality I'm looking for, but I cannot find AddDocument() anywhere?  Checked EnvelopesApi and AccountApi.  What am I missing?  Thanks in advance for any help!

**Comment by gsnavin** [comment]
kslemmer,
Please look into "Composite Templates" following the link below. Here you can add a template and an additional document in one go. Hope this helps.

https://docs.docusign.com/esign/restapi/Envelopes/Envelopes/create/

Naveen

**Comment by kslemmer** [comment]
Hi Naveen,
  Thank you so much for your response.  I was able to get the whole thing working using composite templates, including dropping unused recipients on draft.

Katie
