### ISSUE TITLE
Code consistency and exception exception checks

### ISSUE THREAD

**Issue by bojake** [docusign/DocuSign-.NET-Client#56]
Envelope.Create() checks the null-value state of the key RestSettings members, but the other api methods do not. They should all make these null checks. Maybe a new private method to check these values should be added.

Furthermore, when you try to use “Evenlope.UpdateRecipients” without having completed an Account.Login() you will get a weird exception:

System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Net.WebRequest.Create(String requestUriString)
   at DocuSign.Integrations.Client.RequestBuilder.CreateWebRequest()
   at DocuSign.Integrations.Client.RequestBuilder.MakeRESTRequest()
   at DocuSign.Integrations.Client.Envelope.UpdateRecipients(Recipients recipients, Boolean resendEnvelope)

That should be changed so that a more informative exception, such as “You must login before accessing the service,” should be used. Otherwise, we will all think there is a bug in the API when there is not.

**Comment by InbarGazit** [comment]
@bojake I agree that further checks for initialization and other potential "bugs" can make this package more developer friendly so that if you get an exception - you know exactly what you did wrong. Want to help?

**Comment by bojake** [comment]
i will push up a PR soon, after I get the unit tests working.

**Comment by bojake** [comment]
I am looking for the "why" as to how the Account.Login() magically makes the API call work...

**Comment by InbarGazit** [comment]
there's no magic. The Account.Login() call initializes a bunch of stuff including the baseUrl so we know where to make future API calls.

**Comment by InbarGazit** [comment]
conceptually before you can make API calls, we have to know who you are, right? that's why you need to Login()

**Comment by bojake** [comment]
right, I am looking for a trigger value that I can test in the API call so I can throw an exception that says "hey, login first."

**Comment by bojake** [comment]
Account.LoginAccounts is the value to check. If that is null then Login() is required.

**Comment by InbarGazit** [comment]
you can check baseUrl. if it's null or empty - throw it. I think that's better

**Comment by bojake** [comment]
ok

**Comment by bojake** [comment]
AdvancedScenarios.TemplateEndToEndTest is failing with an invalid envelope error.

**Comment by InbarGazit** [comment]
can you debug it? I think you found an issue with this test :)
I get this error in the RestAPI when trying to update status to send the envelope:
"{\r\n  \"errorCode\": \"ENVELOPE_IS_INCOMPLETE\",\r\n  \"message\": \"The Envelope is not Complete. A Complete Envelope Requires Documents, Recipients, Tabs, and a Subject Line.\"\r\n}"

**Comment by InbarGazit** [comment]
oops, I think I know what this is. it's the subject missing and there's a default you can RestSettings.Instance.EmailSubject and it would fix it. I just tried it, it worked :)

**Comment by bojake** [comment]
ok, let me add an assert in the TemplateEndToEndTest to prevent this from slipping through the cracks again.

**Comment by InbarGazit** [comment]
@bojake let me know when you have the final push you want me to merge. Maybe you should do a new one?

**Comment by bojake** [comment]
it's ready. the last commit was the final change.

**Comment by InbarGazit** [comment]
merged. closing this issue for now
