### ISSUE TITLE
Changing status to void

### ISSUE THREAD

**Issue by peterlord** [docusign/DocuSign-.NET-Client#6]
Hi,

I am having trouble changing status of an envelope to void using the ChangeStatus() method. The problem is that it does not include the required "voided_reason" in the body. It looks like including this within the body of the request if the new status is "void" would do the trick. 

However, I am on a (very) tight deadline. Is there another way you can think of to void an already signed or partially signed envelope. The reason for wanting to void an envelope is in the situation where we need to change one of the signers after the document has been signed.

Thanks,

**Comment by InbarGazit** [comment]
@peterlord  you are correct and adding support for voiding an envelope is something we haven't yet provided. If you will code it yourself (sounds like you already know how and it's pretty straight forward) then just submit this change and we'll take it as part of this library (that's what open source is all about!). I would recommend adding an optional string parameter to UpdateStatus() - this way you don't break others and you don't need to write a new overload (but that option is ok too, maybe Void() or VoidEnvelope() would be fine)

**Comment by InbarGazit** [comment]
closing this since now we have this ability with your latest change. We'll update the nuget package next week with this update. thanks.

**Comment by InbarGazit** [comment]
@peterlord , we're looking for a developer who is using the library to share their experience in the coming conference (I know it's a short notice, it's 2 weeks from now). We can give you a free conference ticket if you can present. Is that something you might be interested in?
