### ISSUE TITLE
Login Authentication failure

### ISSUE THREAD

**Issue by briancamper** [docusign/DocuSign-.NET-Client#63]
Hello,

I have used this dll to login, create and envelope, attaché several "SignHere" tabs, date tabs, and attached the document to sign.  The control works great with my demo account.  But when I point the BaseURL to our production account ( we have went through the API certification ) we are unable to login.  Working with the Docusign support staff, we have verified that the username and password are indeed valid, and I can log into the site directly using those same credentials.  

Using the sample code below, I am able to login to my site:

string strDOCUSIGNURL = ConfigurationManager.AppSettings["DOCUSIGNURL"];
string strDOCUSIGNAPIKEY = ConfigurationManager.AppSettings["DOCUSIGNAPIKEY"];
string strDOCUSIGNPASSWORD = ConfigurationManager.AppSettings["DOCUSIGNPASSWORD"];
string strDOCUSIGNEMAIL = ConfigurationManager.AppSettings["DOCUSIGNEMAIL"];

DocuSign.Integrations.Client.Account account = new DocuSign.Integrations.Client.Account();
                        
account.BaseUrl = strDOCUSIGNURL;
account.Email = strDOCUSIGNEMAIL;
account.Password = strDOCUSIGNPASSWORD;
                          
DocuSign.Integrations.Client.RestSettings RestSettings = DocuSign.Integrations.Client.RestSettings.Instance;
RestSettings.IntegratorKey = strDOCUSIGNAPIKEY;

bool result = account.Login();

This all works great using my Sandbox account, however, when I change to use the production account, I am getting a USER_AUTHENTICATION_FAILED response in the account object, and a false returned from the Login() function.

Any help would be greatly appreciated.

Thanks,

Brian

**Comment by InbarGazit** [comment]
@briancamper  it may be a specific issue for you and not relevant to other user (not sure yet) can you email me directly at inbar.gazit@docusign.com? 
thanks!

**Comment by InbarGazit** [comment]
one thing I wonder about has to do with baseUrl, if your account is not in NA1 (www) then the baseUrl would be different than what you might be using to login (could be na2, eu etc.). Try to check where your account is and consider removing this line:
account.BaseUrl = strDOCUSIGNURL;

**Comment by InbarGazit** [comment]
(however, the login call should always work against www.docusign.net) this is what we call "global auth"

**Comment by InbarGazit** [comment]
you might also be missing some things in DocuSign.Integrations.Client.RestSettings which are needed. As we default the url to demo, you may need to change the DocuSignAddress to be www.docusign.net which I don't see in your snippet...

**Comment by InbarGazit** [comment]
fixed :)
