### ISSUE TITLE
Unable to add multiple documents to an envelope.

### ISSUE THREAD

**Issue by GeekInterface** [docusign/DocuSign-.NET-Client#7]
Hello, 
I am unable to add documents to an envelope.
Example: 
            Byte[] file1 = File.ReadAllBytes(documentPath);
            Byte[] file2 = File.ReadAllBytes(documentPath);
            envelope.AddDocument(file1,"File1.docx",1);
            envelope.AddDocument(file2, "File2.docx",2);

I can only add a single document when I use the Create method.
Example:
 result = envelope.Create(documentPath);

Note: I am using the example code you provided via GitHub to connect to DocuSign.

**Comment by InbarGazit** [comment]
@GeekInterface 
there are 4 overloads for Create(). One of the allow you to specific a list of documents. did you try it?

**Comment by InbarGazit** [comment]
you can also do this in 2 calls like below, but note you haven't yet created the envelope, you can call Create() without any arguments just to create an empty one and then add each one like you did in your code snippet and it would work as well

**Comment by GeekInterface** [comment]
@InbarGazit , Thanks for such a quick response. I did not expect that. 
Here is what I am seeing.

When I call the following statement prior to adding documents as you suggested the method returns false, and I get the following error code "INVALID_CONTENT_TYPE".
             result = envelope.Create();
            // result is false prior to me adding documents.

            Byte[] file1 = File.ReadAllBytes(documentPath);
            Byte[] file2 = File.ReadAllBytes(documentPath);
            envelope.AddDocument(file1, "File1.docx", 1);
            envelope.AddDocument(file2, "File2.docx", 2);


In addition, when I use the overloaded method, the method still returns false, and I get this error "UNABLE_TO_LOAD_DOCUMENT".

            Byte[] file1 = File.ReadAllBytes(documentPath);
            Byte[] file2 = File.ReadAllBytes(documentPath);

            List<Byte[]> files = new List<byte[]>();
            files.Add(file1);
            files.Add(file2);

            List<string> fileNames = new List<string>();
            fileNames.Add("File 1");
            fileNames.Add("File 2");

            result = envelope.Create(files, fileNames);
            // result is false.

If this helps, I am using VS2013 on a windows 8.1 machine. In addition, I also used NuGet to get your package. 

 I look forward to hearing from you.

**Comment by InbarGazit** [comment]
@GeekInterface , just so we can isolate the issue, can you try either a .doc, .pdf or even just a text file and see if result changes?

**Comment by InbarGazit** [comment]
@GeekInterface , one other things. I don't see anywhere in your code that you assign the Envelope.Login property to a valid account object. I assume you had this elsewhere, but just checking. If you can provide full code of your example - I can try to debug it here

**Comment by InbarGazit** [comment]
see examples in the unit tests that are part of the code

**Comment by GeekInterface** [comment]
Here is the full function. I basically tweaked your example code. 

 //==========================================================================================
        // *** Walkthrough #4 - Request Signature on Document
        //==========================================================================================
        private void SignatureRequestOnDocument()
        {
            //*****************************************************************
            // ENTER VALUES FOR FOLLOWING VARIABLES!
            //*****************************************************************
            string AccountEmail = "xxxxxx";
            string AccountPassword = "xxxxx";
            string RecipientEmail = "xxxx";
            string RecipientName = "xxxx";
            string documentPath = @"C:\Users\xxxxx\Documents\testdoc.docx";
            //*****************************************************************

            // user credentials 
            Account account = new Account();
            account.Email = AccountEmail;
            account.Password = AccountPassword;

            // make the login call (retrieves your baseUrl and accountId)
            bool result = account.Login();
            if (!result)
            {
                Console.WriteLine("Login API call failed for user {0}.\nError Code:  {1}\nMessage:  {2}", account.Email, account.RestError.errorCode, account.RestError.message);
                return;
            }

            // create envelope object and assign login info
            Envelope envelope = new Envelope();
            envelope.Login = account;

            // add one signer to the envelope
            envelope.Recipients = new Recipients()
            {
                signers = new Signer[]
                {
                    new Signer()
                    {
                        email = RecipientEmail,
                        name = RecipientName,
                        routingOrder = "1",
                        recipientId = "1"
                    }
                }
            };

            // send the envelope immediately (otherwise set to "created" to save as draft envelope)
            envelope.Status = "sent";

            // email subject is required
            envelope.EmailSubject = "DocuSign .NET Client - Signature Request on Document";
            
            // create envelope and send the signature request (since status is set to "sent")
          
            
            Byte[] file1 = File.ReadAllBytes(documentPath);
            Byte[] file2 = File.ReadAllBytes(documentPath);

            List<Byte[]> files = new List<byte[]>();
            files.Add(file1);
            files.Add(file2);

            List<string> fileNames = new List<string>();
            fileNames.Add("File 1");
            fileNames.Add("File 2");


            result = envelope.Create(files, fileNames);


            if (!result)
            {
                if (envelope.RestError != null)
                {
                    Console.WriteLine("Error code:  {0}\nMessage:  {1}", envelope.RestError.errorCode, envelope.RestError.message);
                    return;
                }
                else
                {
                    Console.WriteLine("Error encountered while requesting signature from template, please review your envelope and recipient data.");
                    return;
                }
            }
            else
            {
                Console.WriteLine("Signature request has been sent to {0}, envelopeId is {1}.", envelope.Recipients.signers[0].email, envelope.EnvelopeId);
            }
        }

**Comment by GeekInterface** [comment]
I will try a pdf and a text file now.

**Comment by GeekInterface** [comment]
Based on my tests, we can currently only add multiple PDFs to an envelope. When I tried Text files, I got the same issues as I did when I tried .docx files.

**Comment by InbarGazit** [comment]
ok, here is the deal, there's a property on the Envelope class called MimeType. This is needed in order to have different other than pdf 
you can find mime types in this link:
http://webdesign.about.com/od/multimedia/a/mime-types-by-file-extension.htm
note if you add 2 files that are not the same, better do it in 2 different calls and set the mime type between calls. We can probably improve this interface in later versions....

**Comment by InbarGazit** [comment]
@GeekInterface , I also wanted to personally invite you to our very first developer conference to be held this coming March in San Francisco. this is exactly the opportunity to meet me and other developers in DocuSign and talk shop. And the cost is very low. See all the information here http://momentum.docusign.com/san-francisco/dev-con/?mc=devcon-github

**Comment by GeekInterface** [comment]
Hey, would you mind if I write a helper class for this to simplify some of the functionality? I can post it on GitHub when I am done.

**Comment by GeekInterface** [comment]
Hey, thanks for inviting me. It sounds very interesting, but it is a bit far from me. I live in Nashville,TN. 

How many people do you have signed up already?

**Comment by InbarGazit** [comment]
I wouldn't mind at all, and you can post it here and we'll take a look and merge it in if it looks ok.
Also, let me know if you got it to work with the .docx files using the mimeType

**Comment by InbarGazit** [comment]
Closing this issue, please let me know if you still need assistance.

**Comment by InbarGazit** [comment]
@GeekInterface ,we're looking for a developer who is using the library to share their experience in the coming conference (I know it's a short notice, it's 2 weeks from now). We can give you a free conference ticket if you can present. Is that something you might be interested in?

**Comment by s-KaiNet** [comment]
I have the same issue when trying to create an envelope with `.docx` document. pdf works just fine, but `.docx` not. I'm using `EnvelopeDefinition` object like in this [Request a signature via email](https://www.docusign.com/developer-center/recipes/request-a-signature-via-email) sample and I didn't find any mime-type on `EnvelopeDefinition` object.   
Can you please help?

**Comment by s-KaiNet** [comment]
Ok, got it. May be helpful for someone: 
This is **NOT** CORRECT:  
```csharp
Document doc = new Document();
doc.DocumentBase64 = System.Convert.ToBase64String(fileBytes);
doc.Name = "Test.docx";
```  
This is **CORRECT**:  
```csharp
Document doc = new Document();
doc.DocumentBase64 = System.Convert.ToBase64String(fileBytes);
doc.FileExtension = "docx";
doc.Name = "Test";
```  
I think you need either update documentation (because this is not clear, that you need to provide an extension separatly) or update a code to extract extension automatically. I'm using nuget `2.0.1` version.
