### ISSUE TITLE
unexpected character encountered while parsing value: <. Path ".line 0, position 0.

### ISSUE THREAD

**Issue by ajayraghuwanshi** [docusign/DocuSign-.NET-Client#72]
When executing below statements:
AccountEnvelopes allEnvelopes = env.GetAccountsEnvelopes(fromDate);
OR 
Newtonsoft.Json.Linq.JObject allEnvelopes = tp.GetTemplate(TemplateId);
getting 'unexpected character encountered while parsing value: <. Path ".line 0, position 0.'
Detailed error:
ERROR : Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at DocuSign.Integrations.Client.AccountEnvelopes.FromJson(String json)
   at DocuSign.Integrations.Client.Envelope.GetAccountsEnvelopes(DateTime fromDate)
   at DocuSignIntegration.DosuSignPOC.btnCreateEnvelope_Click(Object sender, EventArgs e) in c:\Users\f3hx333\Documents\Visual Studio 2013\Projects\DocuSignIntegration\DocuSignIntegration\DosuSignPOC.cs:line 234

**Comment by InbarGazit** [comment]
@ajayraghuwanshi  is this code that used to wrok and now give you to this issue?
what are you trying to do? 
are you using demo?

**Comment by ajayraghuwanshi** [comment]
Yes, i am using Demo, i am new to DosuSign development. I am trying to use methods from ocuSign.Integrations.Client classes to get envelope and send a document to get signed using c#. this initiative is to integrate DocuSign with one of our web application built using asp.net/c# which is used by 10,000 users with my company and external client. We need to integrate DocuSign with this application so we can get Merchants signature and approvals for their account updates. Right now I have a demo developer account. Our requirement is to generate envelope and attach documents to envelope programatically using C#, I have just started on that and this is what i am trying:

   RestSettings.Instance.IntegratorKey = integratorKey;                

                Account acc = new Account();
                acc.AccountId = accountId;
                acc.UserId = username;
                acc.Password = password;
                acc.BaseUrl = baseURL;
                acc.ApiPassword = password;

                DateTime fromDate = DateTime.Now.AddDays(-20);
                
                Envelope env = new Envelope();
                env.Login = acc;
                AccountEnvelopes allEnvelopes = env.GetAccountsEnvelopes(fromDate);

**Comment by InbarGazit** [comment]
ok, so, with this snippit you want to get all the envelopes from the last 20 days? not sure this is what you said in words you wanted to do. If you want to "to generate envelope and attach documents" you need to use one of the Create() methods and figure out where your documents are coming from (either from a file on disk, or passed as stream of bytes). Once you do that, you can either use embedded sending or use templates or just send the envelope right away after placing tags. 
However, if you are trying to do something with envelopes already in the account (like show status or get stats or something) then maybe you need to use GetAccountsEnvelopes() but again, not sure what you are trying to do.  The error you're getting might be cause you have no envelopes at all in this new account (And this edge case might not be covered, so it's a bug, but shouldn't block you)

**Comment by InbarGazit** [comment]
(might be also that you're asking for 20 days and the account is not yet 20 days old so there's some other bug somewhere, might be another edge case, not sure)

**Comment by ajayraghuwanshi** [comment]
I can get information about my account and information about 2 envelopes in my account using rest services, below:

//Get account ifnformation
                string url = "https://demo.docusign.net/restapi/v2/login_information";
                // set request url, method, and headers.  No body needed for login api call
                HttpWebRequest request = initializeRequest(url, "GET", null, username, password, integratorKey);

                // read the http response
                string response = getResponseBody(request);

                // parse baseUrl from response body
                baseURL = parseDataFromResponse(response, "baseUrl");
//Get Envelope info
               url = baseURL + "/envelopes/" + envelopeId;

                // set request url, method, and headers
                request = initializeRequest(url, "GET", null, username, password, integratorKey);

                // read the http response
                response = getResponseBody(request);

But when I trying to use classes from using docusign dll then I am facing issues, like:
RestSettings.Instance.IntegratorKey = integratorKey;

            // user credentials 
            Account account = new Account();
            account.Email = username;
            account.Password = password;

            // make the login call (retrieves your baseUrl and accountId)
            bool result = account.Login();

which is throwing Error:
Login API call failed for user <my email address>
Error Code:  Message:  Non-Protocol Error: SendFailure

I am not sure if i am using these classes properly and if I have correct settings. Do you have any technical document which can guide me on how to use these classes and setting up with environment to connect,create envelope, get envelope, get documents, get status from DocuSign account using c#?

**Comment by ajayraghuwanshi** [comment]
May be I have missed service information which classes are supposed to use, may in config file. Do you have any document about these settings?

**Comment by InbarGazit** [comment]
you can try to run the "unit" tests in the code, they require some changes in a few files to add your email/password IK etc. (like ConfigLoader.cs) and see if these pass for you

**Comment by ajayraghuwanshi** [comment]
Below code is from windows application which is using DocuSign.Integrations.Client. THIS RETURNS FALSE on account.Login() call
	string _username = "Ajay Raghuwanshi";
        string _userId = "ajay.raghuwanshi@firstdata.com";
        string _password = "*****";
        string _integratorKey = "MSCD-*********-****-****-****-***********";
        string _environment = "https://demo.docusign.net";
        string _webServiceUrl = "https://demo.docusign.net/restapi/v2";
        string _webServiceUrl_Login = "https://demo.docusign.net/restapi/v2/login_information";

	private void CheckLogin()
        {
            try
            {
                // configure application's integrator key and webservice url
                RestSettings.Instance.IntegratorKey = _integratorKey;
                RestSettings.Instance.DocuSignAddress = _environment;
                RestSettings.Instance.WebServiceUrl = _webServiceUrl_Login;

                // credentials for sending account
                Account account = new Account();
                account.Email = _userId;
                account.Password = _password;
                account.AccountName = _username;

                // make the Login API call
                bool result = account.Login();

                textBox1.Text = "Login " + result.ToString();
            }
            catch (Exception ex)
            {
                textBox1.Text = "Error: " + ex.ToString();
            }
        }

Here account.Login() call returns false.


This Code Works and returns my Login details:
	private void CheckLoginWithService
        {            
            string baseURL = "";
            try
            {
                // set request url, method, and headers.  No body needed for login api call
                HttpWebRequest request = initializeRequest(_webServiceUrl_Login, "GET", null, _username, _password, _integratorKey);

                // read the http response
                string response = getResponseBody(request);

                // parse baseUrl from response body
                baseURL = parseDataFromResponse(response, "baseUrl");

                //--- display results
                textBox1.Text = string.Format("\nAPI Login Info Call Result: \n\n" + prettyPrintXml(response));
                
            }
            catch (Exception ex)
            {
                textBox1.Text = string.Format("ERROR: " + ex.ToString());
            }
        }

Do you see something wrong with the above code using DocuSign.Integration.Client.dll and why its returning false?

**Comment by InbarGazit** [comment]
RestSettings.Instance.WebServiceUrl needs to be
"https://demo.docusign.net/restapi/v2" but your code sets it to:
"https://demo.docusign.net/restapi/v2/login_information"

**Comment by ajayraghuwanshi** [comment]
Thanks a lot for the clarification, Appreciate you help and patience to answer such basic questions.
After removing '/login_information' and calling this service I got 'True' response. But this response in True all the time, sometime I get False and sometime I get True, Do you know any specific reason for that?

**Comment by ajayraghuwanshi** [comment]
Right now when i call account/Login(), i am getting False, In the morning I was getting True.

**Comment by InbarGazit** [comment]
you get True if the login was successful meaning the API returned 200 (OK) or 201 and not returned an error. for login call, you may get a false if the password/email are wrong or if you use the wrong env (demo vs. production) or if you don't have connectivity etc. etc. (wrong IK is another reason)

**Comment by ajayraghuwanshi** [comment]
I am using same code, userid, pass, keys, everything is same. Now also i have same connectivity as i had in morning, When i called in morning then I got True and now I am getting False. This is really strange.

**Comment by ajayraghuwanshi** [comment]
this morning i was able to run envelope.Create(....) method, I for message in the textbox 'Envelope Created'. I ran below code:

  // configure application's integrator key and webservice url
                RestSettings.Instance.IntegratorKey = _integratorKey;
                RestSettings.Instance.DocuSignAddress = _environment;
                RestSettings.Instance.WebServiceUrl = _environment + "/restapi/v2";

                // credentials for sending account
                Account account = new Account();
                account.Email = _userId;
                account.Password = _password;

                // make the Login API call
                bool result = account.Login();

                if (result)
                {
                    // create envelope object and assign login info
                    Envelope envelope = new Envelope();
                    envelope.Login = account;  // assign account info from above

                    // "sent" to send immediately, "created" to save envelope as draft
                    envelope.Status = "sent";

                    // create a new DocuSign envelope (i.e. server side)
                    envelope.Create(@"C:\Users\f3hx333\documents\visual studio 2013\Projects\DocuSignIntegration\DocuSignIntegration\Documents\Test Document 4.pdf");

                    textBox1.Text = "Envelop Created";
                }
                else
                {
                    textBox1.Text = "Login Failure";
                }

But I didn't see anything in my DocuSign demo account. After successful execution of method envelope.Create(....)  where i am supposed to see created Envelope?

**Comment by InbarGazit** [comment]
you cannot create a sent envelope without recipients and tags. The error would be returned to you in the RestError object if you need to see the error and
also the Create() method returns a bool as well you can check

**Comment by ajayraghuwanshi** [comment]
ok. Thanks. Do you have idea about why I am getting false now compared to True in the morning when calling  account.Login()
I am using same code:
                string _username = "Ajay Raghuwanshi";
		string _userId = "ajay.raghuwanshi@firstdata.com";
		string _password = "**";
		string _integratorKey = "MSCD-***----**********";
		string _environment = "https://demo.docusign.net";

		// configure application's integrator key and webservice url
                RestSettings.Instance.IntegratorKey = _integratorKey;
                RestSettings.Instance.DocuSignAddress = _environment;
                RestSettings.Instance.WebServiceUrl = _environment + "/restapi/v2";

                // credentials for sending account
                Account account = new Account();
                account.Email = _userId;
                account.Password = _password;
                account.AccountName = _username;

                // make the Login API call
                bool result = account.Login();

                textBox1.Text = "Login " + result.ToString();

**Comment by InbarGazit** [comment]
There's a RestError object in the Account class too you can check, you can also get API logs to see if there are any other errors. But if it worked in the morning, it should work now, assuming everything is the same - I don't see why it won't work.

**Comment by ajayraghuwanshi** [comment]
really this account.Login() method call not at all returning True. Is there any way I can debug? or check what exactly is going on in the background?

**Comment by InbarGazit** [comment]
we have unit tests in the code that you can run, did you try them? I know I can get the Login() call to work just fine and I know others do too

**Comment by ajayraghuwanshi** [comment]
Problem was at my end, My company is blocking connection with docusign service. When my laptop is not in my company's network then I can account.Login() returns True, when in company's network it returns false.
I have to work with my network team for this OR I have setup come proxy settings in my application?

**Comment by InbarGazit** [comment]
we do support proxy in this library! However, you'll have to make sure it's indeed a proxy and not some other firewall/restrictions. We found in the past that some customers have other technologies (like AV) that blocks such calls not coming from web browsers. If it's indeed a proxy, you just need to update the Proxy object of the Account or Envelope class before you make API calls

**Comment by ajayraghuwanshi** [comment]
Now this issue is solved, Actually i was missing proxy setting the code, now i have added that i can see call are working within my company network. Thanks for your help.
I have a question. Which class i can use to get templates from DocuSign account? I have to pass data for custom fields in the document in a template and then send it to recipients.

**Comment by InbarGazit** [comment]
Look at the Template class and the GetTemplates() method

**Comment by ajayraghuwanshi** [comment]
With the objects I get from GetTemplates method i see only 3 properties to get ID, Name, Description. How can i get document from that template or how can I pass custom fields values to a document in a template?

**Comment by ajayraghuwanshi** [comment]
and i have one template saved online, but when I execute 
List<TemplateInfo> templates = template.GetTemplates(); 
then I get count returned as 0

**Comment by ajayraghuwanshi** [comment]
Disregard my previous statement,I am getting 1 count, i was getting 0 because of proxy. My question is now: With the objects I get from GetTemplates method i see only 3 properties to get ID, Name, Description. How can i pass custom fields values to a document in this template?

**Comment by InbarGazit** [comment]
you need to create an envelope from your template , right? that's what you're trying to do?

**Comment by InbarGazit** [comment]
there's a method called GetTemplate() that returns all the information given a templateId (it actually just returns json, you would have to parse it)

**Comment by ajayraghuwanshi** [comment]
in the code already available is there any code to parse GetTemplate(_templateID) response? :)

**Comment by InbarGazit** [comment]
var json = template.GetTemplate(templateId);

                    var recipients = json["recipients"];
                    //roles.TemplateName = (string)json["envelopeTemplateDefinition"]["name"];

                    var subject = (string)json["emailSubject"];
                    var blurb = (string)json["emailBlurb"];

These gives you the major things you need, recipients (which include all tags etc.) and subject and blurb. Anything else you need?

**Comment by ajayraghuwanshi** [comment]
Sounds good.. Thanks a lot for your help

**Comment by InbarGazit** [comment]
original issue had to do with proxy, other questions were answered, closing for now

**Comment by ajayraghuwanshi** [comment]
How can I set custom fields added to a document in the template, with the some data from code?

**Comment by InbarGazit** [comment]
custom fields can be added to envelopes regardless of if the envelope was created from a template or not. Look for the CustomFields.textCustomFields in the Envelope object

**Comment by ajayraghuwanshi** [comment]
I have 3 fields in the document with the template exists in my demo account, These fields are UserName, NoteOld and NoteNew. One of the field UserName is showing in the attached image.
![image](https://cloud.githubusercontent.com/assets/16143251/11765552/195b3d38-a11a-11e5-9904-2241d3e81400.png)

I need to set these fields with the data from code. I am adding custom fields to envelope object as:
                    envelope.TemplateId = _templateId; //_templateid is the template id in demo account
                    var customFields = new Dictionary<string, object>();
                    customFields.Add("UserName", "My Name");
                    customFields.Add("NoteOld", "This is old data");
                    customFields.Add("NoteNew", "This is new data");
                    envelope.AddCustomFields(customFields);
                    bool resultEnvelope = envelope.Create();

when code executes, I see envelope getting created with the template, but custom fields data are NOT replaced in the document with the data i am trying to set from code. I don't see any property using which I can retrieve custom fields from document/template and set them from code.

Is above not the correct way of setting fields added to template document?

**Comment by InbarGazit** [comment]
I think there's a confusion about what is "custom fields". This is not the same as "tags". Custom fields are meta-data that is added to the envelope and is hidden and can be used to pass data securely back and forth but I feel what you are trying to do has to do with tags and what's visible in the document which is different. Can you explain the desired behavior?

**Comment by ajayraghuwanshi** [comment]
sure, As i have this screenshot: https://cloud.githubusercontent.com/assets/16143251/11765552/195b3d38-a11a-11e5-9904-2241d3e81400.png and 
![image](https://cloud.githubusercontent.com/assets/16143251/11787988/db69de7a-a24b-11e5-90c9-cc6ef0efd896.png)

I have three fields added to this document in template, these fields are UserName, NoteOld and NoteNew. I want to set data in these fields using code while creating Envelope using this template.
Hope I properly explained this time.

**Comment by ajayraghuwanshi** [comment]
Or is this not the correct way of adding some data using code, to the document in a template while creating envelope?

**Comment by InbarGazit** [comment]
I guess it depends is the answer :) 
One approach is that you have the tags only for data that comes from signers. This means that if you want the document to be customized - you have to do it using HTML or Word or pdf. You just provide DocuSign API with the customized document already and only use tags for downstream data. Another approach is to use tags and add data to the tags, some of it is supported by the library, but not all of it.

**Comment by ajayraghuwanshi** [comment]
i want to add data to the tags, which tags are supported to add data using code? and how can i add data to tags using code?

**Comment by InbarGazit** [comment]
there's some support for this that was added by the community. If you look at the TextTab.cs class you'll see that these types of tabs are now supported and you can add/remove them and update their Value from your code. Some other types of tabs are supported, but not all

**Comment by ajayraghuwanshi** [comment]
you are talking about tabs or tags?

**Comment by InbarGazit** [comment]
very sorry, tags and tabs are confused terminology, I'm talking about the same thing. In our code here we call them "tabs" but they are also called tags. it's just terminology mixup

**Comment by xavierluz** [comment]
I had the same problem with webapi in ASP.NET core, in my case it was because my application needs authentication, then it assigns the annotation "[AllowAnonymous]" and it worked.

  [AllowAnonymous]
  public async Task <IList <IServic >> GetServices () {
        
}
