### ISSUE TITLE
Walkthrough #8 in Examples.cs doesn't work (authorization_invalid_request)

### ISSUE THREAD

**Issue by swlkr** [docusign/DocuSign-.NET-Client#8]
I was trying to get the embedded recipient view but it wasn't working like I thought it would from the API docs, so I forked and changed the Examples.cs file to use the function below GetRecipientView(), GetEmbeddedSignerView() which did work.

I think the culprit for GetRecipientView() is here https://github.com/docusign/DocuSign-.NET-Client/blob/master/DocuSign.Integrations.Client/Envelope.cs#L1467-L1468

**Comment by InbarGazit** [comment]
@swlkr , thanks for your note. I'm not clear as to whether you're saying the example code is wrong or there's a bug in the library, can you clarify?

**Comment by swlkr** [comment]
@InbarGazit I wasn't sure either, so I figured I'd mention both.

**Comment by InbarGazit** [comment]
ok, I think the example is the issue. When using the library you always have to assign a valid logged in user to the Login object of the envelope. I don't see a problem in Envelope.cs, if you think there's - can you let me know exactly what you see?

**Comment by swlkr** [comment]
I'm probably wrong but I thought GetRecipientView was equivalent to this ![2015-02-05 13_57_07](https://cloud.githubusercontent.com/assets/159336/6070167/4516cc00-ad3f-11e4-873f-0f87fce7508e.png) (from: http://iodocs.docusign.com)

Which takes email, username and clientUserId, but Envelope#GetRecipientView just uses the account email/username

**Comment by InbarGazit** [comment]
the GetRecipientView() is a specific one for self-signed envelopes so it's always going to be the person who is logged in.
We have a new method for embedded signing called GetEmbeddedSignerView() which can be used for any signer. Note that non-embedded signing for other recipients is not supported, you have to be the user to sign for this user, cannot sign for user X with credentials of user Y. Hope that makes sense

**Comment by swlkr** [comment]
Ohhhhh ok so it was totally different, yeah that was my misunderstanding.

**Comment by InbarGazit** [comment]
Sean , wanted to also personally invite you to our very first developer conference to be held this coming March in San Francisco. this is exactly the opportunity to meet me and other developers in DocuSign and talk shop. And the cost is very low. See all the information here http://momentum.docusign.com/san-francisco/dev-con/?mc=devcon-github

**Comment by swlkr** [comment]
Hey, thanks :smile:
